DROP TYPE BODY PERSONA2;
DROP TYPE PERSONA2;

CREATE OR REPLACE TYPE PERSONA2 AS OBJECT
(
	CODIGO 			NUMBER,
	NOMBRE 			VARCHAR2(35),
	MAP MEMBER FUNCTION POR_CODIGO RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BODY PERSONA2 AS
	MAP MEMBER FUNCTION POR_CODIGO RETURN NUMBER IS
	BEGIN
		RETURN CODIGO;
	END;
END;
/

SET SERVEROUTPUT ON;
DECLARE
	P1 PERSONA2 := PERSONA2(NULL,NULL);
	P2 PERSONA2 := PERSONA2(NULL,NULL);
BEGIN
	P1.CODIGO := 1;
	P1.NOMBRE := 'JUAN';
	P2.CODIGO := 1;
	P2.NOMBRE := 'MANUEL';
	IF P1 = P2 THEN
		DBMS_OUTPUT.PUT_LINE('OBJETOS IGUALES');
	ELSE
		DBMS_OUTPUT.PUT_LINE('OBJETOS DISTINTOS');
	END IF;
END;
/