DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS OF PERSONA 
(
	CODIGO PRIMARY KEY
);

DESC ALUMNOS;

INSERT INTO ALUMNOS VALUES
(
	1, 'Juan Pérez', DIRECCION ('C/Los manantiales 5', 'GUADALAJARA', 19005), '18/12/1991'
);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, DIR, FECHA_NAC) VALUES (
	2, 'Julia Breña', DIRECCION ('C/Los espártales 25', 'GUADALAJARA', 19004), '18/12/1987'
);

SELECT CODIGO, A.DIR.ciudad 
FROM ALUMNOS A;

SELECT NOMBRE, A.DIR.GET_CALLE() 
FROM ALUMNOS A;

-- SET A.DIR.CIUDAD=LOWER(A.DIR.CIUDAD)
-- WHERE A.DIR.CIUDAD ='GUADALAJARA' ;

-- DELETE ALUMNOS A WHERE A.DIR.CIUDAD='guadalajara';