DROP TYPE DIRECCION;
DROP TYPE PERSONA;
DROP TYPE T_ALUMNO;

CREATE OR REPLACE TYPE DIRECCION AS OBJECT
(
    CALLE VARCHAR2(25),
    CIUDAD VARCHAR2(20),
    CODIGO_POST NUMBER(5),
    MEMBER PROCEDURE SET_CALLE(C VARCHAR2),
    MEMBER FUNCTION GET_CALLE RETURN VARCHAR2
);
/
CREATE OR REPLACE TYPE BODY DIRECCION AS
    MEMBER PROCEDURE SET_CALLE(C VARCHAR2) IS
        BEGIN
            CALLE := C;
        END;

    MEMBER FUNCTION GET_CALLE RETURN VARCHAR2 IS
        BEGIN
            RETURN CALLE;
        END;
END;
/
SET SERVEROUTPUT ON;
DECLARE
    DIR DIRECCION := DIRECCION(NULL,NULL,NULL);
BEGIN
    DIR.SET_CALLE('La Mina, 3') ;
    DBMS_OUTPUT.PUT_LINE(DIR.GET_CALLE) ;
END;
/

CREATE OR REPLACE TYPE PERSONA AS OBJECT (
    CODIGO NUMBER,
    NOMBRE VARCHAR2(35),
    DIREC DIRECCION,
    FECHA_NAC DATE
) ;
/
CREATE OR REPLACE TYPE RECTANGULO AS OBJECT
(
    BASE NUMBER,
    ALTURA NUMBER,
    AREA NUMBER,
    CONSTRUCTOR FUNCTION RECTANGULO (BASE NUMBER, ALTURA NUMBER)
        RETURN SELF AS RESULT.
 );
 /
CREATE OR REPLACE TYPE BODY RECTANGULO AS
    CONSTRUCTOR FUNCTION RECTANGULO (BASE NUMBER, ALTURA NUMBER)
    RETURN SELF AS RESULT
    AS
    BEGIN
        SELF.BASE := BASE;
        SELF.ALTURA := ALTURA;
        SELF.AREA := BASE * ALTURA;
        RETURN;
    END;
END;
/

DECLARE
    DIR DIRECCION := DIRECCION(NULL,NULL,NULL);
    P PERSONA := PERSONA(NULL,NULL,NULL,NULL);
BEGIN
    DIR.CALLE := 'La Mina, 3';
    DIR.CIUDAD := 'Guadalajara';
    DIR.CODIGO_POST : = 19001;
    P.CODIGO := 1;
    P.NOMBRE := 'JUAN' ;
    2
    P.DIREC := DIR;
    P.FECHA_NAC := ‘
    10/11/1988';
END;
/